apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-site
  namespace: portfolio-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-site
  template:
    metadata:
      labels:
        app: portfolio-site
    spec:
      containers:
        - name: portfolio-site
          image: ghcr.io/boudreaux-labs/app-portfolio-site:79b9db4e734e15b80dd07e6152a9164e47b38167
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
