apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-site
  namespace: portfolio-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-site
  template:
    metadata:
      labels:
        app: portfolio-site
    spec:
      containers:
        - name: portfolio-site
          image: ghcr.io/boudreaux-labs/app-portfolio-site:8228cc593a2b7332731dd0bd25857c8a89c2eeae
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
